# Generated by Django 4.1.7 on 2023-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tideturnerweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microplasticfilter',
            name='filter_name',
            field=models.CharField(default='NONAME', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washingmachinesetting',
            name='machine_name',
            field=models.CharField(default='NONAME', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washingmachinesetting',
            name='setting_name',
            field=models.CharField(default='NONAME', max_length=256),
            preserve_default=False,
        ),
    ]
