# Generated by Django 4.1.7 on 2023-04-12 22:48

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tideturnerweb', '0004_alter_washingmachinerun_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washingmachinesetting',
            name='owner',
            field=models.ForeignKey(default=User.objects.filter(is_superuser=True).first().id, on_delete=django.db.models.deletion.CASCADE, related_name='machine_settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
